name: CICDPIPELINE
on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: agent
        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: setup node${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}

            - name: setup pnpm
              uses: pnpm/action-setup@v4
            
                
            - name: install dependencies
              run: pnpm install --frozen-lockfile

            - name: docker image
              run: docker build -t myapp:latest .   

            


    compile:
        runs-on: agent
        needs: build
        steps:
            - name: checkout code
              uses: actions/checkout@v3