name: CICDPIPELINE
on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: agent
        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: setup node${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}

            - name: setup pnpm
              uses: pnpm/setup-pnpm@v4
              with:
                version:10    
                
            - name: install dependencies
              run: pnpm ci

            - name:  build
              run: pnpm run build --if-present  


    compile:
        runs-on: agent
        depends-on: build
        steps:
            - name: checkout code
              uses: actions/checkout@v3